version: '3'

services:
  # zookeeper node for discovery service
  # zookeeper:
    # image: zookeeper:3.5
    # container_name: zookeeper
    # hostname: zookeeper
    # restart: always
    # ports:
    #   - 2181:2181
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVERS: server.1=zookeeper:2888:3888
    # networks:
    #   backend:
    #     ipv4_address: "172.16.238.22"

  raw_server:
    build:
      context: ./server
  
    ports:
      - 8080:8080
      - 4444:4444

    volumes:
      - ./server/app:/app
    
    environment:
      ID: 1
      LB_MAC: ${LB_MAC}

    mac_address: 00:22:22:22:22:22
    networks:
      - backend

  raw_server-2:
    build:
      context: ./server
  
    ports:
      - 8080:8080
      - 4444:4444

    volumes:
      - ./server/app:/app
    
    environment:
      ID: 2
      LB_MAC: ${LB_MAC}

    mac_address: 00:33:33:33:33:33
    networks:
      - backend

networks:
  backend:
    # join existing network, (i build it earlier)
    external: true

    # old configuration

    # internal: true
    # driver: bridge
    # driver_opts:
    #   com.docker.network.bridge.name: br-backend
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: "172.16.238.0/24"
