version: '3'

services:
  discovery:
    build:
      context: ./discovery

    ports:
      - 1337:1337
      - 9999:9999
    
    volumes:
      - ./discovery/app/:/app
    # network_mode: bridge 
    networks:
      backend:
        ipv4_address: 172.16.238.100
      # - default

  raw_server:
    depends_on:
      discovery:
        condition: service_started
    build:
      context: ./server
  
    ports:
      - 8080:8080
      - 4444:4444

    volumes:
      - ./server/app:/app
    
    environment:
      ID: 1
      BR_BACKEND: ${BR_BACKEND}

    mac_address: 00:22:22:22:22:22
    networks:
      - backend

  raw_server-2:
    depends_on:
      discovery:
        condition: service_started

    build:
      context: ./server
  
    ports:
      - 8080:8080
      - 4444:4444

    volumes:
      - ./server/app:/app
    
    environment:
      ID: 2
      BR_BACKEND: ${BR_BACKEND}
      

    mac_address: 00:33:33:33:33:33
    networks:
      - backend

networks:
  backend:
    # join existing network, (i built it earlier)
    external: true

    # old configuration, now created in bootstrap.sh

    # internal: true
    # driver: bridge
    # driver_opts:
    #   com.docker.network.bridge.name: br-backend
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: "172.16.238.0/24"
