FROM alpine:3.14


RUN apk add --update --no-cache bash sudo tcpdump

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 py3-pip && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

RUN pip install scapy
RUN apk add gcc python3-dev py3-psutil

RUN mkdir /app

WORKDIR /app

COPY . /app

# COPY ./app/requirements.txt /tmp/requirements.txt
# RUN pip install -r /tmp/requirements.txt


EXPOSE 8080
EXPOSE 4444

CMD [ "python3", "-m", "http.server", "4444" ]
