FROM alpine:3.14


RUN apk add --update --no-cache bash sudo tcpdump

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 py3-pip && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

RUN pip install scapy
RUN apk add gcc python3-dev py3-psutil

RUN mkdir /app
COPY . /app

WORKDIR /app

EXPOSE 8080
EXPOSE 4444

# make setup.sh work
# RUN chmod 755 ./setup.sh

ENTRYPOINT [ "./setup.sh" ]
CMD [ "python3", "app.py" ]
